spring:
  application:
    name: gateway-service-dev

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 개발 환경에서는 수동 라우팅 사용

      routes:
        # Member Service Routing (개발 환경)
        - id: member-service-dev
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/members/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, gateway-service
            - AddResponseHeader=X-Gateway-Response, true

        # Message Service Routing (개발 환경)
        - id: message-service-dev
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Source, gateway-service
            - AddResponseHeader=X-Gateway-Response, true

# JWT Configuration (개발 환경)
jwt:
  secret: msa-learning-project
  expiration: 86400000 # 24 hours

# Server Configuration
server:
  port: 8080

# Logging Configuration (개발 환경)
logging:
  level:
    com.event.msalearningproject.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
