spring:
  application:
    name: MSALearningProject


  datasource:
    hikari:
      #jdbc-url: jdbc:h2:mem:msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # memory Mode
      jdbc-url: jdbc:h2:~/msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # Embedded Mode
      driverClassName: org.h2.Driver
      username: msa
      password: msa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform:  org.hibernate.dialect.H2Dialect

# Swagger URL Path
springdoc:
  swagger-ui:
    path: /msa/swagger.html

auth:
  jwt:
    secret-key: 807b56a7541af9f1c480dff4f3936b04fb75cece9f7ea40d25c3a57c7786fb7c
    expire-ms : 3600000

