spring:
  application:
    name: MSALearningProject


  datasource:
    hikari:
      #jdbc-url: jdbc:h2:mem:msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # memory Mode
      jdbc-url: jdbc:h2:~/msa;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1 # Embedded Mode
      driverClassName: org.h2.Driver
      username: msa
      password: msa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform:  org.hibernate.dialect.H2Dialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: msa-learning-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Swagger URL Path
springdoc:
  swagger-ui:
    path: /msa/swagger.html

# Kafka Topics
kafka:
  topic:
    default: msa-default-topic
    member: msa-member-topic
    message: msa-message-topic

